# The admin token for the API's admin and dashboard endpoints.
#
# Generated by Terraform on the first apply, and stored ONLY in Secrets
# Manager -- never in Terraform's state or a saved plan:
#
#   - ephemeral "random_password" produces a value that exists only while
#     Terraform runs; ephemeral values are never written to state or plans.
#   - secret_string_wo is a write-only argument: Terraform sends the value to
#     AWS and does not record it.
#
# To see the token (to sign in to the dashboard), read it from Secrets
# Manager with the admin profile:
#   aws secretsmanager get-secret-value --secret-id grain-bin/admin-token --query SecretString --output text
#
# To ROTATE it, bump admin_token_version below and apply: a new value is
# generated and written. The running task picks it up when it next starts
# (deploy.yml forces a new deployment).

locals {
  admin_token_version = 1
}

ephemeral "random_password" "admin_token" {
  length = 48
  # Letters and digits only: the token travels in an HTTP header and in shell
  # commands, where punctuation needs quoting.
  special = false
}

resource "aws_secretsmanager_secret" "admin_token" {
  name        = "${var.name}/admin-token"
  description = "Bearer token for the Grain Bin Telemetry admin API (ADMIN_TOKEN)."

  # Deleted immediately on destroy rather than after the default 7-30 day
  # recovery window, so a destroy-then-apply cycle -- the cost discipline
  # this stack expects -- can recreate a secret with the same name.
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "admin_token" {
  secret_id                = aws_secretsmanager_secret.admin_token.id
  secret_string_wo         = ephemeral.random_password.admin_token.result
  secret_string_wo_version = local.admin_token_version
}
